const $=s=>document.querySelector(s);let products=[],categories=[],customers=[],orders=[];
async function api(action,opts={}){const r=await fetch(`/api?action=${action}`,opts);const d=await r.json();if(!r.ok)throw Error(d.error||"Request failed");return d}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function money(n){return "₹"+Number(n).toLocaleString("en-IN")}
$("#login").onclick=async()=>{try{await api("login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:$("#adminId").value,password:$("#adminPassword").value})});showPanel()}catch(e){$("#loginMsg").innerHTML=`<div class="error">${e.message}</div>`}}
$("#logout").onclick=async()=>{await api("logout",{method:"POST"});location.reload()}
async function showPanel(){$("#loginBox").classList.add("hidden");$("#panel").classList.remove("hidden");await loadAll()}
async function loadAll(){try{const [p,c,cu,o]=await Promise.all([api("products"),api("categories"),api("customers"),api("orders")]);products=p.products;categories=c.categories;customers=cu.customers;orders=o.orders;render()}catch(e){if(String(e.message).includes("Unauthorized")){$("#panel").classList.add("hidden");$("#loginBox").classList.remove("hidden")}else alert(e.message)}}
function render(){ $("#countProducts").textContent=products.length;$("#countCustomers").textContent=customers.length;$("#countOrders").textContent=orders.length;$("#pcat").innerHTML=categories.map(c=>`<option>${esc(c)}</option>`).join("");$("#catList").innerHTML=categories.map(c=>`<span class="chip">${esc(c)} <button onclick="delCat('${esc(c)}')" style="border:0;background:none">×</button></span>`).join("");$("#adminProducts").innerHTML=products.map(p=>`<div class="cart-line"><span><b>${esc(p.name)}</b> · ${esc(p.category)} · ${money(p.price)} · ${esc(p.size)} · Stock ${p.stock}</span><span><button onclick="editProduct('${p.id}')">Edit</button> <button onclick="delProduct('${p.id}')">Delete</button></span></div>`).join("");$("#customers").innerHTML=customers.map(c=>`<div class="cart-line"><span>${esc(c.name||"Customer")} · ${esc(c.phone)}</span><b>${c.points||0} points · ${c.scratchCards||0} cards</b></div>`).join("")||"No customers yet.";$("#orders").innerHTML=orders.map(o=>`<div class="cart-line"><span><b>${esc(o.id)}</b> · ${esc(o.phone)} · ${esc(o.source)} · ${money(o.amount)}<br><small>${esc(o.address||"")}</small></span><span><b>${esc(o.status)}</b>${o.status==="Payment Verified"?` <button onclick="confirmOrder('${o.id}')">Confirm Order</button>`:""}</span></div>`).join("")||"No orders yet."}
$("#saveProduct").onclick=async()=>{try{await api("save-product",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:$("#pid").value,name:$("#pname").value,category:$("#pcat").value,price:$("#pprice").value,size:$("#psize").value,stock:$("#pstock").value,image:$("#pimage").value,description:$("#pdesc").value})});clearProduct();loadAll()}catch(e){alert(e.message)}}
function editProduct(id){const p=products.find(x=>x.id===id);$("#pid").value=p.id;$("#pname").value=p.name;$("#pcat").value=p.category;$("#pprice").value=p.price;$("#psize").value=p.size;$("#pstock").value=p.stock;$("#pimage").value=p.image;$("#pdesc").value=p.description;scrollTo({top:0,behavior:"smooth"})}
function clearProduct(){$("#pid").value="";["pname","pprice","psize","pstock","pimage","pdesc"].forEach(id=>$("#"+id).value="")}
$("#clearProduct").onclick=clearProduct
window.delProduct=async id=>{if(confirm("Delete this product?")){await api("delete-product",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id})});loadAll()}}
$("#saveCat").onclick=async()=>{await api("save-category",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:$("#newCat").value})});$("#newCat").value="";loadAll()}
window.delCat=async name=>{if(confirm("Delete category? Products in this category remain but the category disappears from the selector.")){await api("delete-category",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name})});loadAll()}}
$("#recordSale").onclick=async()=>{try{const d=await api("offline-sale",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phone:$("#salePhone").value,name:$("#saleName").value,amount:$("#saleAmount").value})});$("#saleMsg").innerHTML=`<div class="success">Recorded. Points awarded: <b>${d.pointsAwarded}</b>${d.scratch?` · New scratch card: <b>₹${d.scratch.amount}</b>`:""}</div>`;loadAll()}catch(e){$("#saleMsg").innerHTML=`<div class="error">${e.message}</div>`}}
$("#changePass").onclick=async()=>{try{await api("change-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({currentPassword:$("#oldPass").value,newPassword:$("#newPass").value})});$("#passMsg").innerHTML='<div class="success">Password changed successfully.</div>'}catch(e){$("#passMsg").innerHTML=`<div class="error">${e.message}</div>`}}
loadAll();

window.confirmOrder=async id=>{if(!confirm("Confirm this paid order? Loyalty points will be awarded now."))return;try{const d=await api("confirm-order",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id})});alert(`Order confirmed. Points awarded: ${d.pointsAwarded}${d.scratch?` · Scratch voucher ₹${d.scratch.amount}`:""}`);loadAll()}catch(e){alert(e.message)}}
